function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (09-Jan-2019 14:20:31)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = (((((1.5-var(1))+(var(1).*var(2))).^2.0)+(((2.25-var(1))+(var(1).*(var(2).^2.0))).^2.0))+(((2.625-var(1))+(var(1).*(var(2).^3.0))).^2.0));
end % ipoptObjective