function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (10-Apr-2019 12:19:45)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = ((var(1).*sum((((var(184:1:273).^2.0)+(var(185:1:274).^2.0))./2.0)))-var(92));
end % ipoptObjective