function [J] = ipoptJacobianStructure(var)
%IPOPTJACOBIANSTRUCTURE
%
% Auto-generated by COALESCE package (10-Jan-2019 16:50:02)
%
% Copyright 2013-2014 Mikhail S. Jones

	iJ = [1:1:200,1:1:200,201:1:399,201:1:399,201:1:399,201:1:399,201:1:399,400:1:598,400:1:598,400:1:598,400:1:598,400:1:598,599,600,601,602]';
	jJ = [602:1:801,2:1:201,203:1:401,202:1:400,1+zeros(1,199),402:1:600,403:1:601,403:1:601,402:1:600,1+zeros(1,199),602:1:800,603:1:801,202,402,401,601]';
	sJ = 1 + zeros(1,2394);
	J = sparse(iJ, jJ, sJ, 602, 801);

end % ipoptJacobianStructure