function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (09-Jan-2019 14:20:44)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1]';
	jg = [2,1]';
	sg(2,1) = 0; % Pre-allocation
	sg(1) = (100.0.*(2.0.*(var(2)-(var(1).^2.0))));
	sg(2) = ((100.0.*((2.0.*-((2.0.*var(1)))).*(var(2)-(var(1).^2.0))))+(-2.0.*(1.0-var(1))));
	g = sparse(ig, jg, sg, 1, 2);

end % ipoptGradient