function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (09-Jan-2019 14:20:29)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1]';
	jg = [2,1]';
	sg(2,1) = 0; % Pre-allocation
	sg(1) = (((-((var(2)+47.0)).*(cos(sqrt(abs(((var(2)+(var(1)./2.0))+47.0)))).*((sign(((var(2)+(var(1)./2.0))+47.0))./2.0)./sqrt(abs(((var(2)+(var(1)./2.0))+47.0))))))+-(sin(sqrt(abs(((var(2)+(var(1)./2.0))+47.0))))))-(var(1).*(cos(sqrt(abs((var(1)-(var(2)+47.0))))).*((-(sign((var(1)-(var(2)+47.0))))./2.0)./sqrt(abs((var(1)-(var(2)+47.0))))))));
	sg(2) = ((-((var(2)+47.0)).*(cos(sqrt(abs(((var(2)+(var(1)./2.0))+47.0)))).*(((sign(((var(2)+(var(1)./2.0))+47.0)).*0.5)./2.0)./sqrt(abs(((var(2)+(var(1)./2.0))+47.0))))))-((var(1).*(cos(sqrt(abs((var(1)-(var(2)+47.0))))).*((sign((var(1)-(var(2)+47.0)))./2.0)./sqrt(abs((var(1)-(var(2)+47.0)))))))+sin(sqrt(abs((var(1)-(var(2)+47.0)))))));
	g = sparse(ig, jg, sg, 1, 2);

end % ipoptGradient