function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (10-Jan-2019 16:49:48)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = ((100.0.*((var(2)-(var(1).^2.0)).^2.0))+((1.0-var(1)).^2.0));
end % ipoptObjective