function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (10-Jan-2019 16:49:53)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1]';
	jg = [1,2]';
	sg(2,1) = 0; % Pre-allocation
	sg(1) = ((((2.0.*(-1.0+var(2))).*((1.5-var(1))+(var(1).*var(2))))+((2.0.*(-1.0+(var(2).^2.0))).*((2.25-var(1))+(var(1).*(var(2).^2.0)))))+((2.0.*(-1.0+(var(2).^3.0))).*((2.625-var(1))+(var(1).*(var(2).^3.0)))));
	sg(2) = ((((2.0.*var(1)).*((1.5-var(1))+(var(1).*var(2))))+((2.0.*(var(1).*(2.0.*var(2)))).*((2.25-var(1))+(var(1).*(var(2).^2.0)))))+((2.0.*(var(1).*(3.0.*(var(2).^2.0)))).*((2.625-var(1))+(var(1).*(var(2).^3.0)))));
	g = sparse(ig, jg, sg, 1, 2);

end % ipoptGradient