function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (10-Jan-2019 16:49:44)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = ((-((var(2)+47.0)).*sin(sqrt(abs(((var(2)+(var(1)./2.0))+47.0)))))-(var(1).*sin(sqrt(abs((var(1)-(var(2)+47.0)))))));
end % ipoptObjective