function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (09-Jan-2019 14:18:58)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1]';
	jg = [1]';
	sg(1,1) = 0; % Pre-allocation
	sg(1) = 1.0;
	g = sparse(ig, jg, sg, 1, 801);

end % ipoptGradient