function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (27-Mar-2019 16:27:39)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = (var(1).*sum(((var(1276:1:1365)+var(1277:1:1366))./2.0)));
end % ipoptObjective