function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (16-Jan-2019 21:05:08)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1+zeros(1,50),1+zeros(1,50)]';
	jg = [1,614:1:663,615:1:664]';
	sg(101,1) = 0; % Pre-allocation
	sg(1) = sum((((var(614:1:663).^2.0)+(var(615:1:664).^2.0))./2.0));
	sg(2:51) = (var(1).*((2.0.*var(614:1:663))./2.0));
	sg(52:101) = (var(1).*((2.0.*var(615:1:664))./2.0));
	g = sparse(ig, jg, sg, 1, 1021);

end % ipoptGradient