function [c] = ipoptConstraints(var)
%IPOPTCONSTRAINTS
%
% Auto-generated by COALESCE package (09-Jan-2019 14:18:58)
%
% Copyright 2013-2014 Mikhail S. Jones

	c(602,1) = 0; % Pre-allocation
	c(1:199) = ((var(203:1:401)-var(202:1:400))-(((var(1)./199.0).*((var(602:1:800).*sin(var(2:1:200)))+(var(603:1:801).*sin(var(3:1:201)))))./2.0));
	c(200:398) = ((var(403:1:601)-var(402:1:600))-(((var(1)./199.0).*((var(602:1:800).*cos(var(2:1:200)))+(var(603:1:801).*cos(var(3:1:201)))))./2.0));
	c(399:597) = ((var(603:1:801)-var(602:1:800))-(((var(1)./199.0).*((9.81.*cos(var(2:1:200)))+(9.81.*cos(var(3:1:201)))))./2.0));
	c(598) = var(202);
	c(599) = var(402);
	c(600) = var(602);
	c(601) = var(401);
	c(602) = var(601);
end % ipoptConstraints