function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (10-Jan-2019 16:49:42)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = ((0.26000000000000001.*((var(1).^2.0)+(var(2).^2.0)))-((0.47999999999999998.*var(1)).*var(2)));
end % ipoptObjective