function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (27-Mar-2019 16:27:39)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1+zeros(1,90),1+zeros(1,90)]';
	jg = [1,1276:1:1365,1277:1:1366]';
	sg(181,1) = 0; % Pre-allocation
	sg(1) = sum(((var(1276:1:1365)+var(1277:1:1366))./2.0));
	sg(2:91) = (var(1).*0.5);
	sg(92:181) = (var(1).*0.5);
	g = sparse(ig, jg, sg, 1, 1821);

end % ipoptGradient