%MATLABFUNCTIONGENERATOR MATLAB function generation object.
%
% Copyright 2014 Mikhail S. Jones

classdef  MatlabFunctionGenerator < FunctionGenerator

  % PUBLIC METHODS ========================================================
  methods
    function this = MatlabFunctionGenerator(argsIn, argsOut, name)
    %MATLABFUNCTIONGENERATOR MATLAB function generation object constructor.

      % Call superclass constructor
      this = this@FunctionGenerator(argsIn, argsOut, name);
    end % FunctionGenerator

    function writeHeader(this)
    %WRITEHEADER Create file and write function header.

      % Open new file to write without automatic flushing (W vs w)
      this.fid = fopen(['auto/' this.name '.m'], 'W');

      % Create argument strings
      out = sprintf('%s,', this.argsOut{:});
      out = out(1:end-1);
      in = sprintf('%s,', this.argsIn{:});
      in = in(1:end-1);

      % Write file header
      fprintf(this.fid, 'function [%s] = %s(%s)\n', out, this.name, in);
      fprintf(this.fid, '%%%s\n', upper(this.name));
      fprintf(this.fid, '%%\n');
      fprintf(this.fid, '%% Auto-generated by COALESCE package (%s)\n', ...
        datestr(now));
      fprintf(this.fid, '%%\n');
      fprintf(this.fid, '%% Copyright 2013-2014 Mikhail S. Jones\n');
      fprintf(this.fid, '\n');
    end % writeHeader

    function writeIndex(this, index, name)
    %WRITEINDEX Write vectorized index.

      % Initialize string
      str = '';

      % Loop through each cell of array
      for i = 1:numel(index)
        % Check for scalar indexes
        if numel(index{i}) == 1
          % Write as scalar index
          str = [str sprintf('%g,', index{i})];

        % Check for repeating indexes
        elseif all(diff(index{i}) == 0)
          % Write as vectorized index
          str = [str sprintf('%g+zeros(1,%d),', index{i}(1), numel(index{i}))];
          % Note: scalar + zeros(m,n) is the fastest way to do this without
          % using an intermediate step, much faster than ones and a
          % little faster than repmat

        % Check for monotonically increasing indexes
        elseif all(diff(diff(index{i})) == 0)
          % Write as vectorized index
          str = [str sprintf('%g:%g:%g,', index{i}(1), index{i}(2) - index{i}(1), index{i}(end))];

        else
          % Write as full index
          str = [str sprintf('%g,', index{i})];
        end % if
      end % for

      % Write to file
      fprintf(this.fid, '\t%s = [%s]'';\n', name, str(1:end-1));
    end % writeIndex

    function writeExpression(this, expression, name)
    %WRITEEXPRESSION Write vectorized symbolic expression.

      matlabCode(expression, name, this.fid); % TODO: Move function here
    end % writeExpression

    function writeFooter(this)
    %WRITEFOOTER Create file and write function footer.

      % Write function end and close file
      fprintf(this.fid, 'end %% %s', this.name);
      fclose(this.fid);
    end % writeHeader
  end % methods
end % classdef
