function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (10-Jan-2019 16:49:40)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1]';
	jg = [1,2]';
	sg(2,1) = 0; % Pre-allocation
	sg(1) = (2.0.*var(1));
	sg(2) = (2.0.*var(2));
	g = sparse(ig, jg, sg, 1, 2);

end % ipoptGradient