function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (10-Apr-2019 12:19:45)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1+zeros(1,90),1+zeros(1,90),1]';
	jg = [1,184:1:273,185:1:274,92]';
	sg(182,1) = 0; % Pre-allocation
	sg(1) = sum((((var(184:1:273).^2.0)+(var(185:1:274).^2.0))./2.0));
	sg(2:91) = (var(1).*((2.0.*var(184:1:273))./2.0));
	sg(92:181) = (var(1).*((2.0.*var(185:1:274))./2.0));
	sg(182) = -1.0;
	g = sparse(ig, jg, sg, 1, 547);

end % ipoptGradient