function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (10-Jan-2019 16:49:35)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = (-0.0001.*((abs(((sin(var(1)).*sin(var(2))).*exp(abs((100.0-(sqrt(((var(1).^2.0)+(var(2).^2.0)))./3.1415926535897931))))))+1.0).^0.10000000000000001));
end % ipoptObjective