function [c] = ipoptConstraints(var)
%IPOPTCONSTRAINTS
%
% Auto-generated by COALESCE package (18-Jan-2019 14:05:32)
%
% Copyright 2013-2014 Mikhail S. Jones

	c(508,1) = 0; % Pre-allocation
	c(1:100) = ((var(3:1:102)-var(2:1:101))-((var(1)./100.0).*var(103:1:202)));
	c(101:200) = ((var(104:1:203)-var(103:1:202))-((var(1)./100.0).*(((16.817142857142859.*(-(cos(var(2:1:101)))-((0.5.*cos(var(2:1:101)))./2.0)))+(var(305:1:404)./0.29166666666666669))-(0.050000000000000003.*var(103:1:202)))));
	c(201:301) = var(305:1:405);
	c(302) = var(2);
	c(303) = var(103);
	c(304) = var(102);
	c(305) = var(203);
	c(306:406) = (var(305:1:405)+var(204:1:304));
	c(407:507) = (var(204:1:304)-var(305:1:405));
	c(508) = var(1);
end % ipoptConstraints