function [J] = ipoptJacobianStructure(var)
%IPOPTJACOBIANSTRUCTURE
%
% Auto-generated by COALESCE package (18-Jan-2019 14:05:32)
%
% Copyright 2013-2014 Mikhail S. Jones

	iJ = [1:1:100,1:1:100,1:1:100,1:1:100,101:1:200,101:1:200,101:1:200,101:1:200,101:1:200,201:1:301,302,303,304,305,306:1:406,306:1:406,407:1:507,407:1:507,508]';
	jJ = [3:1:102,2:1:101,1+zeros(1,100),103:1:202,104:1:203,103:1:202,1+zeros(1,100),2:1:101,305:1:404,305:1:405,2,103,102,203,305:1:405,204:1:304,204:1:304,305:1:405,1]';
	sJ = 1 + zeros(1,1410);
	J = sparse(iJ, jJ, sJ, 508, 405);

end % ipoptJacobianStructure