function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (11-Feb-2019 17:38:20)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = ((((var(1).*sum((((var(2:1:101).^2.0)+(var(3:1:102).^2.0))./2.0)))+((var(1)+var(2022)).*sum((((var(1012:1:1111).^2.0)+(var(1013:1:1112).^2.0))./2.0))))+(var(1).*sum((((var(103:1:202).^2.0)+(var(104:1:203).^2.0))./2.0))))+((var(1)+var(2022)).*sum((((var(1113:1:1212).^2.0)+(var(1114:1:1213).^2.0))./2.0))));
end % ipoptObjective