function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (09-Jan-2019 14:20:39)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1]';
	jg = [1,2]';
	sg(2,1) = 0; % Pre-allocation
	sg(1) = ((0.26000000000000001.*(2.0.*var(1)))-(var(2).*0.47999999999999998));
	sg(2) = ((0.26000000000000001.*(2.0.*var(2)))-(0.47999999999999998.*var(1)));
	g = sparse(ig, jg, sg, 1, 2);

end % ipoptGradient