function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (09-Jan-2019 14:20:50)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1]';
	jg = [2,1]';
	sg(2,1) = 0; % Pre-allocation
	sg(1) = (100.0.*((sign((var(2)-(0.01.*(var(1).^2.0))))./2.0)./sqrt(abs((var(2)-(0.01.*(var(1).^2.0)))))));
	sg(2) = ((100.0.*(((sign((var(2)-(0.01.*(var(1).^2.0)))).*-((0.01.*(2.0.*var(1)))))./2.0)./sqrt(abs((var(2)-(0.01.*(var(1).^2.0)))))))+(0.01.*sign((var(1)+10.0))));
	g = sparse(ig, jg, sg, 1, 2);

end % ipoptGradient