function [g] = ipoptGradient(var)
%IPOPTGRADIENT
%
% Auto-generated by COALESCE package (18-Jan-2019 14:05:32)
%
% Copyright 2013-2014 Mikhail S. Jones

	ig = [1,1+zeros(1,100),1+zeros(1,100)]';
	jg = [1,204:1:303,205:1:304]';
	sg(201,1) = 0; % Pre-allocation
	sg(1) = sum(((var(204:1:303)+var(205:1:304))./2.0));
	sg(2:101) = (var(1).*0.5);
	sg(102:201) = (var(1).*0.5);
	g = sparse(ig, jg, sg, 1, 405);

end % ipoptGradient