function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (09-Jan-2019 14:20:35)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = ((((-20.0.*exp((-0.20000000000000001.*sqrt((((0.5.*var(1)).*var(1))+((0.5.*var(2)).*var(2)))))))-exp((0.5.*cos((((6.2831853071795862.*var(1)).*var(1))+((6.2831853071795862.*var(2)).*var(2)))))))+20.0)+2.7182818284590455);
end % ipoptObjective