function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (10-Jan-2019 16:49:51)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = ((1.0+((((var(1)+var(2))+1.0).^2.0).*(((((19.0-(14.0.*var(1)))+(3.0.*(var(1).^2.0)))-(14.0.*var(2)))+((6.0.*var(1)).*var(2)))+(3.0.*(var(2).^2.0))))).*(30.0+((((2.0.*var(1))-(3.0.*var(2))).^2.0).*(((((18.0-(32.0.*var(1)))+(12.0.*(var(1).^2.0)))+(48.0.*var(2)))-((36.0.*var(1)).*var(2)))+(27.0.*(var(2).^2.0))))));
end % ipoptObjective