function [J] = ipoptJacobian(var)
%IPOPTJACOBIAN
%
% Auto-generated by COALESCE package (09-Jan-2019 14:20:48)
%
% Copyright 2013-2014 Mikhail S. Jones

	iJ = []';
	jJ = []';
	sJ = [];
	J = sparse(iJ, jJ, sJ, 0, 2);

end % ipoptJacobian