function [f] = ipoptObjective(var)
%IPOPTOBJECTIVE
%
% Auto-generated by COALESCE package (10-Jan-2019 16:49:55)
%
% Copyright 2013-2014 Mikhail S. Jones

	f(1,1) = 0; % Pre-allocation
	f(1) = (-((1.0+cos((12.0.*sqrt(((var(1).^2.0)+(var(2).^2.0)))))))./((0.5.*((var(1).^2.0)+(var(2).^2.0)))+2.0));
end % ipoptObjective